config/routes.rb
Dustin::Application.routes.draw do

  root :to => "pages#home"

  match "/contact", :to => "pages#contact"
  match "/about",   :to => "pages#about"
  match "/privacy", :to => "pages#privacy"
  match "/terms",   :to => "pages#terms"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def privacy
  end

  def terms
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="span-24 last">
  <center>
    [ <%= link_to "Terms", terms_path %> 
    | <%= link_to "Privacy", privacy_path %> 
    | &copy 2011 
    | <%= link_to "About", about_path %> 
    | <%= link_to "Contact", contact_path %> ]
  </center>
</div>

app/views/layouts/_header.html.erb
<div class="span-2">
  WHITESPACE
</div>
<div class="span-20">
  LOGOBAR
</div>
<div class="span-2 last">
  USERBAR
</div>

app/views/layouts/_javascripts.html.erb
<%= javascript_include_tag :defaults %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->    

<%= stylesheet_link_tag 'blueprint/screen', :media => "screen" %>
<%= stylesheet_link_tag 'custom' %>

<!--[if lt IE 8]>
  <link rel="stylesheet" href="css/blueprint/ie.css" type="text/css" media="screen, projection">
<![endif]-->

<%= stylesheet_link_tag 'css3buttons' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dustin</title>
  <%= render 'layouts/stylesheets' %>
  <%= render 'layouts/javascripts' %>
  <%= csrf_meta_tag %>
</head>
<body>

  <div class = "container">
  
    <%= render 'layouts/header' %>

    <%= yield %>
    
    <%= render 'layouts/footer' %>
  
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pages/privacy.html.erb
<h1>Pages#privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>